# Generated by Django 2.2.4 on 2019-08-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heatmap.Hashtag')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heatmap.Tweet')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtag',
            field=models.ManyToManyField(through='heatmap.Relationship', to='heatmap.Hashtag'),
        ),
    ]
